language: go

pre_install:
  - wget https://github.com/bep/s3deploy/releases/download/v2.1.0/s3deploy_2.1.0_Linux-64bit.deb
  - sudo dpkg -i s3deploy_2.1.0_Linux-64bit.deb

install:
  - rm -rf public || exit 0

script:
  - s3deploy -source=static/ -region=eu-west-1 -bucket=denis.evsyukov.org -key "$AWS_KEY_ID" -secret "$AWS_ACCESS_KEY" -force -v

env:
  global:
  - secure: "ZTAyq7PzZnUsxF7WttucnzyKuOSECKzbF1iNxeBOUQ0h2de1EPBaykLyDQXPddf3oXRsbUA3BzA4JtVu2X+7fLZRNZL1n1gUjF1s5Jt2k8Ps7kz/nawbdFJ/y6P6s8BwRJ3BhDV2s6UeQF1C8buFBQwXbWECUZl2nh1efL14yzI="
  - secure: "FjfahNoPH1rQJ4VuTl2frmdaf9aoLQRvSFk4caqXT005ooGeyPZT3lVjwTfAqOsmcF6QRgre3Ic5eSiYvF3f2lq8LYI1XQWEY/DzDO402Ro3wYlhvhiHkIZK3hAmCtgpMA1vSonRDBiez7pbMLLpAqXYHF9MUmZSnWEr45c9CdU="
