language: go

go:
  - 1.11.x

install:
  - rm -rf public || exit 0

script:
  - echo "Hello World!"

deploy:
  provider: s3
  access_key_id: "$AWS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY"
  bucket: "denis.evsyukov.org"
  skip_cleanup: true
  region: "eu-west-1"
  acl: public_read
  local_dir: static
  detect_encoding: true
  cache_control: "max-age=0"

env:
  global:
  - secure: "ZTAyq7PzZnUsxF7WttucnzyKuOSECKzbF1iNxeBOUQ0h2de1EPBaykLyDQXPddf3oXRsbUA3BzA4JtVu2X+7fLZRNZL1n1gUjF1s5Jt2k8Ps7kz/nawbdFJ/y6P6s8BwRJ3BhDV2s6UeQF1C8buFBQwXbWECUZl2nh1efL14yzI="
  - secure: "FjfahNoPH1rQJ4VuTl2frmdaf9aoLQRvSFk4caqXT005ooGeyPZT3lVjwTfAqOsmcF6QRgre3Ic5eSiYvF3f2lq8LYI1XQWEY/DzDO402Ro3wYlhvhiHkIZK3hAmCtgpMA1vSonRDBiez7pbMLLpAqXYHF9MUmZSnWEr45c9CdU="
