[Settings]
ID = "8cec229d-0d5d-4980-aa87-df9eb89d64a8"

[build]
publish = "public/"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.47.1"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.47.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
 
[[redirects]]
  from = "https://fervent-chandrasekhar-509ce9.netlify.com/*"
  to = "https://denis.evsyukov.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://denis.evsyukov.org/*"
  to = "https://denis.evsyukov.org:splat"
  status = 301
  force = true

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Cache-Control = "max-age=0"
    X-UA-Compatible = "IE=Edge"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "/assets/pretty.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000"
