[Settings]
ID = "8cec229d-0d5d-4980-aa87-df9eb89d64a8"

[build]
  publish = "public"
  command = ""
 
[[redirects]]
  from = "http://fervent-chandrasekhar-509ce9.netlify.com/*"
  to = "https://denis.evsyukov.org/:splat"

[[redirects]]
  from = "http://denis.evsyukov.org/*"
  to = "https://denis.evsyukov.org:splat"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Cache-Control = "max-age=0"
    X-UA-Compatible = "IE=Edge"
[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "max-age=31536000"
[[headers]]
  for = "/assets/pretty.jpg"
  [headers.values]
    Cache-Control = "max-age=31536000"
