name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install s3deploy
        run:  |
          S3DEPLOY_DOWNLOAD=s3deploy_${S3DEPLOY_VERSION}_Linux-64bit.tar.gz
          set -x
          set -e
          wget https://github.com/bep/s3deploy/releases/download/v${S3DEPLOY_VERSION}/${S3DEPLOY_DOWNLOAD}
          tar xvzf ${S3DEPLOY_DOWNLOAD} s3deploy
        env:
          S3DEPLOY_VERSION: 2.6.0
      - name: Deploy to S3
        run: ./s3deploy -bucket denis.evsyukov.org -public-access -region eu-west-2 -max-delete -1 -source sources/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
