name: Deploy Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "sources"
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_ACTOR: juev
    - name: Purge cache
      uses: jakejarvis/cloudflare-purge-action@master
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

